### ISSUE TITLE
Upload issue of beta table

### ISSUE THREAD

**Issue by daisukeadachi** [jonathandroth/PretrendsPower#2]
Hi,

I hope this finds you well. I am writing to ask you a question about the [online app](https://jonathandroth.shinyapps.io/pretrendspowerapp/).

I checked that I can upload your example [beta table](https://github.com/jonathandroth/PretrendsPower/blob/master/example_beta.csv) on the app, but I encounter an error when I tried to upload [my beta table](https://github.com/jonathandroth/PretrendsPower/files/9039030/beta_l_emp.csv), which I tried my best to mimic the structure in your beta table. Attached is the screenshot of the error code, where I do not know where I can check the log:
![Screenshot 2022-07-04 at 13 22 57](https://user-images.githubusercontent.com/27741570/177145998-8f47a23c-a353-4cf7-8ce3-ac32000ab939.png)

Could you help me figure out what went wrong? Thanks so much.

Best regards,
Daisuke Adachi

**Comment by jonathandroth** [comment]
Hi Daisuke,

Thanks for your email!

I think you did not know do anything wrong. However, you also need to
upload the remaining two CSVs (with the covariance and hypothesized
difference in trends) in order to get the results from the Shiny. There
appears to have been a bug with the error messaging on the Shiny app so
that this was very unclear. I have pushed an update that should hopefully
make it much clearer! Sorry about that. Let me know if it works or if you
have any other issues.

Best,
Jon

**Comment by daisukeadachi** [comment]
Hi Jon,

This is great. I could perform the pre-test on the app now. 

The app was great overall especially because I use mac and encounter the same problem as in [another thread on your repo](https://github.com/jonathandroth/pretrends/issues/2). But the app gave me the workaround, so thanks so much!

Best,
Daisuke

**Comment by jonathandroth** [comment]
Awesome, glad to hear!
